# Site settings
title: Emmanouil Maragkakis
email: mns.marag@gmail.com
description: 'Personal website for Emmanouil ''Manolis'' Maragkakis'
baseurl: ""
url: "http://www.emaragkakis.com"
github_username:  mnsmar
scholar_username: F3yZjVMAAAAJ

# Build settings
kramdown:
    input: GFM
permalink: pretty
# paginate: 5
# paginate_path: "blog/page:num/"
exclude: ["node_modules", "workbench"]
