# Site settings
title: Emmanouil Maragkakis
email: mns.marag@gmail.com
description: 'Personal website for Emmanouil ''Manolis'' Maragkakis'
baseurl: ""
url: "http://www.emaragkakis.com"
twitter_username: mnsmar
github_username:  mnsmar
googleplus_username: +EmmanouilMaragkakis
researchgate_username: Manolis_Maragkakis
# facebook_username:  manolis.maragkakis.58

# Build settings
markdown: redcarpet
# markdown: kramdown
highlighter: pygments
permalink: pretty
# paginate: 5
# paginate_path: "blog/page:num/"
exclude: ["node_modules", "workbench"]
